-- Fathom clone — Supabase schema (run in the Supabase SQL editor)
-- No auth: a single implicit user, so there is no users table.

create extension if not exists "pgcrypto";

-- Clean re-run support
drop table if exists chat_messages    cascade;
drop table if exists action_items     cascade;
drop table if exists highlights       cascade;
drop table if exists summaries        cascade;
drop table if exists transcript_segments cascade;
drop table if exists participants     cascade;
drop table if exists meetings         cascade;

-- ---------------------------------------------------------------- meetings
create table meetings (
  id               uuid primary key default gen_random_uuid(),
  title            text not null,
  description      text,
  meeting_type     text not null default 'general'
                   check (meeting_type in ('general','sales','one_on_one','technical','planning')),
  started_at       timestamptz not null,
  duration_seconds integer not null check (duration_seconds > 0),
  video_url        text,
  thumbnail_url    text,
  share_token      text not null unique default encode(gen_random_bytes(12), 'hex'),
  created_at       timestamptz not null default now(),
  -- full-text search over title + description
  search_tsv       tsvector generated always as (
                     to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description,''))
                   ) stored
);
create index meetings_started_at_idx on meetings (started_at desc);
create index meetings_search_idx     on meetings using gin (search_tsv);

-- ------------------------------------------------------------ participants
create table participants (
  id         uuid primary key default gen_random_uuid(),
  meeting_id uuid not null references meetings(id) on delete cascade,
  name       text not null,
  email      text,
  role       text,                      -- e.g. host, attendee
  is_host    boolean not null default false,
  avatar_color text,                    -- UI hint for speaker bubbles
  unique (meeting_id, name)
);
create index participants_meeting_idx on participants (meeting_id);

-- ----------------------------------------------------- transcript_segments
-- One row per line of speech, or per screen-share event shown inline.
create table transcript_segments (
  id             uuid primary key default gen_random_uuid(),
  meeting_id     uuid not null references meetings(id) on delete cascade,
  participant_id uuid references participants(id) on delete set null,
  segment_index  integer not null,
  segment_type   text not null default 'speech'
                 check (segment_type in ('speech','screen_share_start','screen_share_end')),
  start_seconds  numeric(8,2) not null check (start_seconds >= 0),
  end_seconds    numeric(8,2),
  text           text not null,         -- for screen share rows: what was shared
  search_tsv     tsvector generated always as (to_tsvector('english', text)) stored,
  unique (meeting_id, segment_index)
);
create index segments_meeting_time_idx on transcript_segments (meeting_id, start_seconds);
create index segments_search_idx       on transcript_segments using gin (search_tsv);

-- ---------------------------------------------------------------- summaries
-- One summary per (meeting, template). Generated by Groq or seeded.
create table summaries (
  id             uuid primary key default gen_random_uuid(),
  meeting_id     uuid not null references meetings(id) on delete cascade,
  template       text not null check (template in ('general','sales','action_items')),
  purpose        text not null,                         -- "Meeting Purpose"
  key_takeaways  jsonb not null default '[]'::jsonb,    -- ["bullet", ...]
  custom_prompt  text,                                  -- set via Customize button
  generated_at   timestamptz not null default now(),
  unique (meeting_id, template)
);
create index summaries_meeting_idx on summaries (meeting_id);

-- --------------------------------------------------------------- highlights
-- Clickable timestamps inside the summary that seek the video.
create table highlights (
  id            uuid primary key default gen_random_uuid(),
  meeting_id    uuid not null references meetings(id) on delete cascade,
  summary_id    uuid references summaries(id) on delete cascade,
  start_seconds numeric(8,2) not null check (start_seconds >= 0),
  label         text not null,
  position      integer not null default 0
);
create index highlights_meeting_idx on highlights (meeting_id, position);

-- ------------------------------------------------------------- action_items
create table action_items (
  id            uuid primary key default gen_random_uuid(),
  meeting_id    uuid not null references meetings(id) on delete cascade,
  assignee_id   uuid references participants(id) on delete set null,
  description   text not null,
  start_seconds numeric(8,2),           -- where in the call it was said
  is_completed  boolean not null default false,
  completed_at  timestamptz,
  created_at    timestamptz not null default now()
);
create index action_items_meeting_idx on action_items (meeting_id);

-- ------------------------------------------------------------ chat_messages
-- Ask Fathom history. meeting_id NULL = global chat on the dashboard sidebar.
create table chat_messages (
  id         uuid primary key default gen_random_uuid(),
  meeting_id uuid references meetings(id) on delete cascade,
  role       text not null check (role in ('user','assistant')),
  content    text not null,
  created_at timestamptz not null default now()
);
create index chat_messages_meeting_idx on chat_messages (meeting_id, created_at);

-- ------------------------------------------------------------------ search
-- Global search across titles and transcripts; returns one row per hit.
create or replace function search_meetings(q text)
returns table (
  meeting_id    uuid,
  title         text,
  match_type    text,
  snippet       text,
  start_seconds numeric
)
language sql stable as $$
  select m.id, m.title, 'title', m.title, null::numeric
    from meetings m
   where m.search_tsv @@ websearch_to_tsquery('english', q)
  union all
  select m.id, m.title, 'transcript', s.text, s.start_seconds
    from transcript_segments s
    join meetings m on m.id = s.meeting_id
   where s.search_tsv @@ websearch_to_tsquery('english', q)
$$;

-- No auth: the backend uses the service-role key, so RLS stays disabled.
